// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvetpibfwrgggsrhvesv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2ZXRwaWJmd3JnZ2dzcmh2ZXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjM3NjcsImV4cCI6MjA3MjAzOTc2N30.I9VqD9nDWtvK2-yKWQCDkcLgLdbX3mlrKb1cEcLp6YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});